### ISSUE TITLE
fix: ACG text color

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#670]
* [x] Dark text is barely readable, and the white text should probably not be white:
  ![image](https://user-images.githubusercontent.com/282899/153866419-9b1ecfd1-33f2-42c7-b703-e6cd1c40297d.png)
  ![image](https://user-images.githubusercontent.com/282899/153869382-e68e50d4-e063-42c0-b67f-9e70877a328f.png)
* [x] Reconsider coloring scheme. The ACG in the paper (and in general in `screenshotMode`) looks too washed out
* [x] Make sure, we maximize contrast. If background is bright, text color should probably be `0` or very close to it. Also make sure, that the color is the same everywhere. It currently seems inconsistent. I searched for `" color:"` in `styles.css` (ignore highlight coloring, which is currently disabled):
  ```css
  .loc-label {
    /* color: #333; */
    white-space: nowrap;
    color: rgba(0, 0, 0);
  }

  /* ... */

  .theme-mode-dark .loc-label {
    color: #222;
  }

  /* ... */
  .theme-mode-dark .research-mode .async-node {
    color: #333;
  }
  ```
